Fake PR
ParadoxGameConverters/CK2ToEU4 pull request #198
Opened 2020-09-01 23:15 UTC by Elfangor567

I apologize for the bad coding.

2020-09-12 22:28 UTC, Zemurin requested changes

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Flags/Flags.cpp
> +std::set<std::string> CK2::Flags::checkReformation()
rename to "prepareReformationList", or fillReformationList or similar. Checks are usually functions that return bool or similar. Semantics.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Flags/Flags.cpp
> +bool CK2::Flags::getInvasion()
this is redundant. Simply return count("aztec_explorers") in .h file like for others. World.h will store that flag anyway.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Flags/Flags.h
> +		bool getInvasion();
here - return count() instead.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Religions/Religion.cpp
> +		auto featureVector = featureList.getStrings();
auto means copy, no need:
const auto& featureVector = commonItems::stringList(theStream).getStrings();

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Religions/Religions.cpp
> +	registerRegex("[A-Za-z0-9\\_:.-]+", commonItems::ignoreItem);
delete this line.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +	reformedFeatures();
similarly semantics, rename to "compileReformedFeatures" or similar. "reformedFeatures" sounds like a storage object.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +	// religions.getReformedReligion();
delete all unnecessary comments. we know what functions return by hovering over them, comments are more useful when they explain either what the function does or intricacies of why an algorithm behaves in an odd manner.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +	// All Reformed Religions
for example this is a good comment as it breaks up the function into logical segments, and that's helpful.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +	for (auto religion: reformedReligionMapper.getReligionEntries())
likewise, if you're not modifying religion, use const auto&

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +		for (auto tempReform: religions.getReformedReligion().find(reformation)->second)
because you are modifying tempReligion, auto is proper here.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +	for (auto unreformed: unreformationList)
ditto.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.cpp
> +		noReformation = false;
you're using double negative. It's not intuitive. rather use wasReformation and default it to false, and then set it true here.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +void EU4::World::outputReformedReligions(const Configuration& theConfiguration,  bool noReformation,
move actual religion file construction (if there was reformation) out of here and into outReligion.cpp. Outworld doesn't do literal dumps.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapper.h
> +	explicit ReformedReligionMapper(std::istream& theStream);							 // testing
not testing. drop comment.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		color = commonItems::singleItem(mods, theStream);
no. color is color, from commonItems::Color.
you load it with
color = commonItems::Color::Factory().getColor(theStream)
and you store it in:
std::optional\<commonItems::Color\> color;
in .h file.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/CK2WorldTests/Flags/FlagsTests.cpp
> +TEST(CK2World_FlagsTests, doesItCatchFlags)
add test to confirm it's empty if input is blank.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/CK2WorldTests/Flags/FlagsTests.cpp
> +	input << "worldIsReal=yes\nworldGovernment=yes\nworldReligion=no";
breaking this up makes it more readable.
input << "worldIsReal=yes\n"
input << "norldGovernment=yes\n"
etc.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/CK2WorldTests/Religions/ReligionTests.cpp
> +TEST(CK2World_ReligionTests, doesItCatchFeatures)
blank test as well.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/CK2WorldTests/Religions/ReligionsTests.cpp
> +TEST(CK2World_ReligionsTests, doesItCatchReligionName)
blank test.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/CK2WorldTests/Religions/ReligionsTests.cpp
> +}
add test for multiple items.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMapperTests.cpp
> +TEST(Mappers_ReformedReligionMapperTests, doesItCatchAnything)
add blank test.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMapperTests.cpp
> +	input << "a_religion_reformed = {\n}" << "a_new_religion_reformed = {\n}" << "a_newer_religion_reformed = {\n}";
break into multiple lines.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMapperTests.cpp
> +TEST(Mappers_ReformedReligionMapperTests, doesItIgnoreComments)
no need for this, this test is done by the parser itself.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "color = { 3 33 333 }\n}";
don't do this. 333 is an invalid input for Color and once you swap to commonItems::Color this will throw exception.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	ASSERT_EQ("3 33 333 ", test);
we have aplenty of color tests I thin elsewhere, do a search in tests folder for color. titleTests has some.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "country = {\ncountry_power = 9001\ncountry_weakness = 0}\n}";
break apart.

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "province = {\nprovince_size = big\nprovince_strength = weak}\n}";
ditto

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "country_as_secondary = {\nmingplosion_power = 100\n}\n}";
ditto

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "unique_modifiers = {\nisUlm = yes\n}\n}";
ditto

2020-09-12 22:28 UTC, Zemurin commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "not_unique_modifiers = {\ncan_raid_self = yes\ncan_ignore_treaties = yes\n}\n}";
ditto

2020-09-12 23:30 UTC, Elfangor567 commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		color = commonItems::singleItem(mods, theStream);
Why would I do that?

2020-09-13 00:30 UTC, Idhrendur requested changes

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Religions/Religion.cpp
> +		auto featureVector = featureList.getStrings();
I think it should be ```const auto featureVector = commonItems::stringList(theStream).getStrings();```

Otherwise it's getting a reference to a member of an object falling out of scope. The language turns the copy into a move if there's no intermediate variable name.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Religions/Religions.h
> +	class Religion;
Redundant, delete.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.h
> +	std::string getName() { return name; }
All returned items should be [[nodiscard]]

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.h
> +	std::string getName() { return name; }
Instead of returning std::string, return const auto&. Repeat for all other returned strings.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "icon = 1\n}";
Split all inputs over multiple lines.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +	input << "icon = 1\n}";
Also, inputs should include the opening equals and brace:
```
input << "= {\n";
input << "\ticon = 1\n";
input << "}";

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +#include "../../CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.h"
Add tests for the default conditions

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMappingTests.cpp
> +#include "../../CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.h"
Add tests for all setters

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		countryModifiers = countryModifiers + "\n" + mod;
This looks like something where you want to actually be using a container to handle sub-strings.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		provinceModifiers = provinceModifiers + "\n" + mod;
Ditto

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		secondary = secondary + "\n" + mod;
Ditto

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		nonUniqueMechanics = nonUniqueMechanics + "\n" + mod;
Ditto

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4Tests/MapperTests/ReformedReligionMapper/ReformedReligionMapperTests.cpp
> +	input << "a_religion_reformed = {\n}";
Split into multiple lines

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +	outputReformedReligions(theConfiguration, wasNoReformation, unreligionReforms, religionReforms);
You can just call the getter functions here instead of setting variables people would have to scroll to remember where they came from.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +			unReformedReligions << unreligion.getName() << " = {\n" <<
Add an output function that takes a mappers::ReformedReligionMapping and handles all these details. At this level of abstraction you want

```
for (auto unreligion: unreligionReforms)
{
	unReformedReligions << unreligion << "\n";
}
```

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +			reformedReligions << religion.getName() << " = {\n" <<
Ditto

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/EU4World.h
> +	void outputReformedReligions(const Configuration& theConfiguration, bool noReformation, std::vector<mappers::ReformedReligionMapping>, std::vector<mappers::ReformedReligionMapping>) const;
All the vectors should be const vector& instead.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/World.h
> +	Flags flags;
If this is only ever used when in the relevant lambda, make it a local variable there instead of a member variable here.

2020-09-13 00:30 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/World.cpp
> +	for (auto reformation: reformationList)
const auto&

2020-09-13 00:36 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +			unReformedReligions << unreligion.getName() << " = {\n" <<
This all ended up in outReligion.

2020-09-13 00:37 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +			reformedReligions << religion.getName() << " = {\n" <<
Same

2020-09-13 09:31 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/World.h
> +	Flags flags;
No, I told him to move those bools out of the lambda as I'm trying to get rid of processing in lambdas. Current setup is fine, with flags permanenty being accessible.

2020-09-13 09:33 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Flags/Flags.h
> +		bool isGreek() { return greekReformation; }
IsGreek is used but I think by internal function to see if the hellenic reformation is greek or roman. outWorld depends on it, so this functionality must remain. Tests are always good.

2020-09-13 09:34 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Flags/Flags.h
> +		bool aztecReformation() { return flags.count("aztec_reformation"); }
These are supposed to be external so any function can poke at global flags and see their status. Tests, not private.

2020-09-13 16:19 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Flags/Flags.h
> +		bool isGreek() { return greekReformation; }
If only used by internal functions, it can just be moved to private, then. And no need (or way) to test private functions so its all good.

2020-09-13 16:24 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Flags/Flags.h
> +		bool isGreek() { return greekReformation; }
It is used once in World.cpp to set a variable.

2020-09-13 16:24 UTC, Idhrendur commented on CK2ToEU4Tests/CK2WorldTests/Flags/FlagsTests.cpp
> +
You can delete some of the blank lines. In most cases, you want to use them to highlight three sections in your test:
 * Setting up
 * Doing something
 * Checking the results of the tings you did.

2020-09-13 16:35 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Religions/Religion.cpp
> +		auto featureVector = featureList.getStrings();
So no &?

2020-09-13 16:54 UTC, Elfangor567 commented on CK2ToEU4Tests/CK2WorldTests/Religions/ReligionTests.cpp
> +	input << "features = {\nfeature_1 feature_2 feature_3\n}";
That is what the data file looks like.
features=
			{
				religion_proselytizing religion_feature_norse religion_relentless religion_temporal_head 
			}

2020-09-13 17:03 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Religions/Religion.cpp
> +		auto featureVector = featureList.getStrings();
No &

2020-09-13 17:04 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outWorld.cpp
> +			unReformedReligions << unreligion.getName() << " = {\n" <<
I'd still like to see the details in a lower-level function.

2020-09-13 17:10 UTC, Elfangor567 commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		countryModifiers = countryModifiers + "\n" + mod;
Why?

2020-09-13 17:40 UTC, Idhrendur commented on CK2ToEU4Tests/CK2WorldTests/Religions/ReligionTests.cpp
> +	input << "features = {\nfeature_1 feature_2 feature_3\n}";
Yep, so the code should be more like
```
input << "features=\n";
input << "{\n";
input << "\treligion_proselytizing religion_feature_norse religion_relentless religion_temporal_head\n";
input << "}";
```

2020-09-13 18:11 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		countryModifiers = countryModifiers + "\n" + mod;
At first glance, you're spending a lot of time searching through strings to create a neatly-ordered list and avoid duplicates. That's not really the strength of strings, but rather the strength of a std::set<std::string> or somesuch.

2020-09-13 18:20 UTC, Elfangor567 commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		countryModifiers = countryModifiers + "\n" + mod;
I don't access the countryModifiers except to output it. Why would I want to make it a set of strings?

2020-09-13 20:32 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/ReformedReligionMapper/ReformedReligionMapping.cpp
> +		countryModifiers = countryModifiers + "\n" + mod;
Ah, if it's just stored then nevermind.

2020-09-14 17:53 UTC, Zemurin approved these changes

2020-09-15 00:06 UTC, Idhrendur approved these changes

2020-09-16 06:04 UTC, closed without merging