Monumental update
ParadoxGameConverters/CK2ToEU4 pull request #268
Opened 2021-05-09 18:37 UTC by Elfangor567

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/World.cpp
> +	if (!commonItems::DoesFileExist(theConfiguration.getEU4Path() + "/dlc/dlc106_leviathan/dlc106.dlc"))
You might consider a one-line ```IsLeviathanDlcPresent()``` so the flow is kept on the logic instead of the details.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/World.cpp
> +	if (!commonItems::DoesFileExist(theConfiguration.getEU4Path() + "/dlc/dlc106_leviathan/dlc106.dlc"))
Reverse the logic so the positive condition is first. Less thinking for any readers/maintainers.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/EU4World.cpp
> +	importCK2Provinces(sourceWorld, commonItems::DoesFileExist(theConfiguration.getEU4Path() + "/dlc/dlc106_leviathan/dlc106.dlc"));
As this comes up in two places, definitely put a utility function somewhere.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outMonument.h
> +			outMonument(const Configuration theConfiguration, std::set<std::string> premades); //Premade Monuments
Configuration&

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outMonument.h
> +			outMonument(const Configuration theConfiguration, std::set<std::string> premades); //Premade Monuments
const std::set<std::string>&

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +	if (premades.count("wonder_pyramid_giza"))
Use contains instead of count for all of these.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +	// Goes through each upgrade that a wonder has and creates vectors for the bonuses, only done for up to a max of 4 bonuses.
This kind of logic should be in EU4 world, not the output function.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +			for (auto modifiers: provinceModifiers)
Somethings weird with the indentation here. Run the code formatter on all your changed files:
Ctrl+A to select everything.
Ctrl+K, F to format.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Province/EU4Province.h
> +	[[nodiscard]] auto getHasMonument() const { return hasMonument; }
Just ```hasMonument()```

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/EU4World/Province/EU4Province.cpp
> +		setHasMonument();
You can just set the variable directly instead of using a function. And if that's the only use of this function, remove it.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.h
> +	[[nodiscard]] auto getIsBase() { return isBase; }
Just ```isBase()```

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp
> +		CreateBuildTrigger(theStream);
As painful as it can be, it's best to move this to a separate helper class.

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp
> +		AddProvinceSet(theStream);
Ditto

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp
> +		AddAreaSet(theStream);
Ditto

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp
> +		AddCountrySet(theStream);
Ditto

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +		if (premadeMonuments.count(wonder.second->getType()))
Use contains

2021-05-09 23:40 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.h
> +	std::set<std::string> linkMonuments(const Wonders& wonders, Characters characters); // Leviathan DLC
```const Characters&```

2021-05-10 09:05 UTC, Zemurin requested changes

2021-05-17 20:41 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		type = typeStr.getString();
This does not work and results in an error.

2021-05-17 20:43 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		type = typeStr.getString();
Got it I think. Is it type = commonItems::singleString(theStream).getString(); ?

2021-05-17 20:49 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +			fillConstructionHistory(tempStream);
Results in an error. 
"initial value of reference to non-const must be an lvalue"

2021-05-17 20:51 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +			builder = commonItems::singleLlong(theStream).getLlong(); //This should get the first builder
?

2021-05-17 20:52 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		if (date < 1 || commonItems::singleInt(theStream).getInt() < date) //Gets the earliest date
?

2021-05-17 20:53 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		upgrades.insert(commonItems::singleString(theStream).getString());
I think I mentioned it before, this requested form only results in an error
namespace "commonItems" has no member "getString"

2021-05-17 21:07 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outMonument.h
> +			outMonument(const Configuration theConfiguration, std::set<std::string> premades); //Premade Monuments
This creates errors, most saying that there is no instance of the overloaded function (.count()) that matches that function list.

2021-05-17 21:09 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +	if (premades.count("wonder_pyramid_giza"))
contains has the same error as count, should I still replace it?

2021-05-17 21:11 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +			for (auto modifiers: provinceModifiers)
No, I personally forced it to be formatted that way. It matches how it will turn out in the outputted file.

2021-05-17 21:22 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Province/EU4Province.h
> +	[[nodiscard]] auto getHasMonument() const { return hasMonument; }
Results in an error. I think because the method and the variable have the same name?
"cannot deduce type"

2021-05-17 21:24 UTC, Elfangor567 commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.h
> +	[[nodiscard]] auto getIsBase() { return isBase; }
Same as before with getHasMonument()

2021-05-17 21:25 UTC, Elfangor567 commented on CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp
> +		CreateBuildTrigger(theStream);
Why?

2021-05-17 21:28 UTC, Elfangor567 commented on CK2ToEU4/Data_Files/configurables/monuments/great_projects/!00_converted_monuments.txt
> +##This file needs to be blank, trust us - Converter Team
I forgot to delete the text when I copied the 00 file to make that one?

2021-05-17 21:31 UTC, Elfangor567 commented on CK2ToEU4/Data_Files/configurables/monuments_mappings.txt
> +# These are the religious bonuses you get for monuments
There is a maximum of 4 buffs per monument, so no need to worry about overstacking.
Which buffs are you referring to? I was going off the bonuses of some of the vanilla monuments such as the Great Wall for inspiration.

2021-05-17 21:33 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +			existentMonuments.emplace(premadeMonuments.count(wonder.second->getType()));
I believe this is colloquially known as "incompetence".

2021-05-17 21:34 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +				wonder.second->addUpgrade("generic_religious_upgrade_3");
If the wonder is level 3 already we don't need to add more stuff.
This checks to see if it is lower than level 3, then adds stuff accordingly based on level.

2021-05-17 21:38 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +				wonder.second->addUpgrade("generic_religious_upgrade_3");
Basically, the wonder needs upgrades for all 3 possible levels it can have.

2021-05-17 21:41 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Output/outMonument.h
> +			outMonument(const Configuration theConfiguration, std::set<std::string> premades); //Premade Monuments
Nevermind, I was putting the & inside the <> when it needed to be after.

2021-05-17 21:43 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +			builder = commonItems::singleLlong(theStream).getLlong(); //This should get the first builder
How would I ditch it then?

2021-05-17 21:44 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		if (date < 1 || commonItems::singleInt(theStream).getInt() < date) //Gets the earliest date
It is an int?

2021-05-17 21:56 UTC, Zemurin commented on CK2ToEU4/Data_Files/configurables/monuments_mappings.txt
> +# These are the religious bonuses you get for monuments
If there's a limit then fine, I think, but even 4 is too much. Remember that people *will* build this junk everywhere.

2021-05-17 22:08 UTC, Zemurin requested changes

2021-05-17 22:08 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		if (date < 1 || commonItems::singleInt(theStream).getInt() < date) //Gets the earliest date
read the date into some variable and then use the variable. So not use it inside an ID because it won't be read at all if date >= 1 and then you've broken the stream.

2021-05-17 22:08 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +		if (date < 1 || commonItems::singleInt(theStream).getInt() < date) //Gets the earliest date
you're reading an int, so name the variable dateInteger or something. dates are usually our own custom class called date so it's doubly confusing.

2021-05-17 22:08 UTC, Zemurin commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +				wonder.second->addUpgrade("generic_religious_upgrade_3");
Yes but you're writing nonsense. A monument at getstage()=1 will satisfy all conditions here and will get upgrade_1 and upgrade_2.
Monument at getstage=2 will get just upgrade_2.
monument at getstage=3 will get nothing at all.

2021-05-17 22:29 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +				wonder.second->addUpgrade("generic_religious_upgrade_3");
Let me just step through how I see it and tell me where I went wrong
else if (wonder.second->getStage() < 3) // If the wonder is stage 3, don't bother with the other checks, it doesn't need them.
if (wonder.second->getStage() < 1) // If monument is less than stage 1 (0), add upgrade #1
if (wonder.second->getStage() < 2) //If monument is less than stage 2  (0, 1), add upgrade #2 
// (0, 1, 2) add upgrade #3

2021-05-17 22:29 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
> +				wonder.second->addUpgrade("generic_religious_upgrade_3");
Err, ignore the links

2021-05-18 01:48 UTC, Idhrendur commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
> +			fillConstructionHistory(tempStream);
Ah, how annoying. Nevermind then.

2021-05-18 22:49 UTC, IhateTrains commented on CK2ToEU4/Source/EU4World/Output/outMonument.cpp
> +	if (premades.count("wonder_pyramid_giza"))
Yes, makes intent clearer.

2021-05-20 21:53 UTC, Elfangor567 commented on CK2ToEU4/Source/CK2World/Wonders/Wonder.h
> +	std::string trueDate = "0";
Are you asking me to make a new date class? For what purpose?

2021-05-20 21:59 UTC, Elfangor567 commented on CK2ToEU4/Source/EU4World/Province/EU4Province.cpp
> +void buildMonument()
Relic of dropped plan. My apologies.

2021-06-13 16:40 UTC, merged